### ISSUE TITLE
animation bug

### ISSUE THREAD

**Issue by 435352980** [flowtsohg/mdx-m3-viewer#24] opened 2019-08-26 08:24 UTC
it looks like missing some animation on render
using mdx-m3-viewer
![8月-26-2019 16-16-43](https://user-images.githubusercontent.com/35485428/63676399-6f64e200-c81d-11e9-9e1f-acdc42e8f492.gif)

real behavior
![8月-26-2019 16-15-13](https://user-images.githubusercontent.com/35485428/63676452-8d324700-c81d-11e9-896d-73c25e56c247.gif)

the mdx files
[HHY.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/3540144/HHY.zip)

**Comment by 435352980** [comment] 2019-08-27 11:39
this model's face render error
[TohsakaRin.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/3545872/TohsakaRin.zip)

**Comment by 435352980** [comment] 2019-08-29 06:29
it somes like a bug from animation.getValue function
and if i set forced always true on modelinstance class the animation loop would be fine
but i don't know how to fix it :(

**Comment by flowtsohg** [comment] 2019-08-31 13:20
The issue with the wings is actually the alpha value of the geoset animation.
When it goes below 0.75, the bone that uses the animation is considered not visible, and thus stops getting updated.
The rules of when different things are visible/active aren't known. I've wasted a whole lot of time trying to fix these issues in the past, without ever getting a solution that worked for all models, unfortunately.
When you forced forced to be true, it simply ignored optimizations such as skipping updating nodes when they are not visible, therefore it "fixed" the issue for you.

I am not quite sure what you mean with the other model.

**Comment by 435352980** [comment] 2019-09-01 03:34
Oh, Thanks! 
I love this library, it's really powerful!

About the animation issue that i mean:
using mdx-m3-viewer
![9月-01-2019 11-06-11](https://user-images.githubusercontent.com/35485428/64071251-905b8600-cca8-11e9-806e-c8c72f45e90f.gif)
real
![9月-01-2019 11-06-01](https://user-images.githubusercontent.com/35485428/64071254-95b8d080-cca8-11e9-9981-6ed72504dd62.gif)
This is the model named "TohsakaRin" that i was uploaded.

It seems the "force" only effect on animation loop
![9月-01-2019 11-05-50](https://user-images.githubusercontent.com/35485428/64071261-05c75680-cca9-11e9-8952-422571710ff1.gif)

if only use the default value on  animatedobject>getFloatValue function
![0FF184FF-6CF8-4134-9873-5EE33EB0C358](https://user-images.githubusercontent.com/35485428/64071320-5c816000-ccaa-11e9-8d17-594f43c78331.png)
![9月-01-2019 11-24-56](https://user-images.githubusercontent.com/35485428/64071355-2d1f2300-ccab-11e9-98a9-9b1bae533044.gif)

**Comment by flowtsohg** [comment] 2019-09-01 13:07
Ah, I no longer have an easy setup with which to load custom textures, so I didn't notice those issues.

For the wings, it's the same issue as the bones - when the geoset's alpha (via the geoset animation) drops below 0.75, the geoset is considered not visible, as can be seen [in the shader](https://github.com/flowtsohg/mdx-m3-viewer/blob/master/src/viewer/handlers/mdx/shaders.js#L62).
As the comment there states, and as I mentioned above, it's clearly not correct, but I could never make it correct for all models.

I'll try to update the sanity test client later to load custom textures and look at the other model.

**Comment by flowtsohg** [comment] 2019-09-04 11:12
As far as I can tell, there isn't any issue with the eye sprite animation.
Are you using the library directly, or via the Hive?

That being said, when the textures don't load with the model (e.g. they can't be found because they are custom), and are reloaded later, it won't work properly, because sprite animations are joined into a texture atlas when the model is loaded.
If the textures aren't valid when the texture atlas is created, it won't be correct.

**Comment by 435352980** [comment] 2019-09-04 15:31
Here is the online demo pege to preview the model

https://435352980.github.io/tw-qc-static/#/mdx

And my pathResolver is
```js
const pathSolver = dir => [
  'resources/' +
    dir
      .replace('Replaceabletextures', 'ReplaceableTextures')
      .replace('replaceabletextures', 'ReplaceableTextures')
      .replace('splats', 'Splats')
      .replace('Teamglow', 'TeamGlow')
      .replace('textures', 'Textures')
      .replace('BLP', 'blp'),
  dir.substr(dir.lastIndexOf('.')),
  true,
];
```
I am sorry that I forgot this.

**Comment by flowtsohg** [comment] 2019-09-04 16:49
Odd. Are you using the latest version? I can't access the viewer on your page, so I can't check much on it.

**Comment by flowtsohg** [comment] 2019-09-05 11:12
It seems like I indeed added a regression and then fixed it only in my local copy.
https://github.com/flowtsohg/mdx-m3-viewer/blob/master/src/viewer/handlers/mdx/layer.js#L103
Can you change this line locally to the following, and see if it fixes the issue?

```javascript
let textureIds = unique(this.animations.KMTF.getValues().map((array) => array[0]));
```

Thanks

**Comment by 435352980** [comment] 2019-09-05 11:39
![9月-05-2019 19-37-37](https://user-images.githubusercontent.com/35485428/64338603-cd12de80-d014-11e9-9986-beef4d874d64.gif)

**Comment by flowtsohg** [comment] 2019-09-05 11:51
It looks like I made more changes and never committed them, so I just did. Can you test now please? :)

**Comment by 435352980** [comment] 2019-09-05 11:55
Okay, what should I do?

**Comment by flowtsohg** [comment] 2019-09-05 12:00
Update to the latest commit and rebuild the library

**Comment by 435352980** [comment] 2019-09-05 12:15
:)
![9月-05-2019 20-13-40](https://user-images.githubusercontent.com/35485428/64340913-d18dc600-d019-11e9-8519-75ea0e628c10.gif)

**Comment by flowtsohg** [comment] 2019-09-05 12:17
Nice. I'll keep this issue open, for as long as the visibility rules aren't known, which might be forever :P

**Closed** 2019-09-07 23:53 UTC
